### ISSUE TITLE
Matrixx Android 14 rear fingerprint is not working since January 2024 Updates

### ISSUE THREAD

**Issue by zahidmgsk** [zahidmgsk/android_device_google_bramble#1]
Logcat for the issue is as follows:

```
02-07 14:15:45.683  2557  2580 V WindowManagerShell: Transition animation finished (aborted=false), notifying core (#26)android.os.BinderProxy@cc81e0c@0
02-07 14:15:45.685  1873  2150 V WindowManager: Finish Transition #26: created at 02-07 14:15:45.175 collect-started=0.033ms request-sent=0.121ms started=3.391ms ready=11.152ms sent=45.525ms finished=509.715ms
02-07 14:15:45.685  3004  5620 E FrameEvents: addRelease: Did not find frame.
02-07 14:15:45.688  2557  2580 V WindowManagerShell: Track 0 became idle
02-07 14:15:45.688  2557  2580 V WindowManagerShell: All active transition animations finished
02-07 14:15:45.704  1873  3897 W ActivityTaskManager: Duplicate finish request for r=ActivityRecord{8744832 u0 com.android.settings/.biometrics.fingerprint.FingerprintEnrollEnrolling t10 f}}
02-07 14:15:45.705  3004  3004 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.app.Activity$$ExternalSyntheticLambda0@3f17fa4
02-07 14:15:45.705  1873  3032 D CoreBackPreview: Window{c5145fb u0 com.android.settings/com.android.settings.biometrics.fingerprint.FingerprintEnrollEnrolling}: Setting back callback null
02-07 14:15:45.706  1873  3897 W InputManager-JNI: Input channel object 'c5145fb com.android.settings/com.android.settings.biometrics.fingerprint.FingerprintEnrollEnrolling (client)' was disposed without first being removed with the input manager!
02-07 14:15:45.989  2557  2580 D ShellBackPreview: initAnimation mMotionStarted=false
02-07 14:15:45.989  1873  3897 D CoreBackPreview: Focused window found using getFocusedWindowToken
02-07 14:15:45.990  1873  3897 D CoreBackPreview: startBackNavigation currentTask=Task{262cdf6 #10 type=standard A=1000:com.android.settings.root}, topRunningActivity=ActivityRecord{7b22489 u0 com.android.settings/.biometrics.fingerprint.FingerprintSettings t10}, callbackInfo=OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@dfc253e, mPriority=-1, mIsAnimationCallback=false}, currentFocus=Window{6c240c0 u0 com.android.settings/com.android.settings.biometrics.fingerprint.FingerprintSettings}
02-07 14:15:45.990  1873  3897 D CoreBackPreview: Previous Destination is Activity:ComponentInfo{com.android.settings/com.android.settings.Settings$CombinedBiometricSettingsActivity} Task:Task=10 removedContainer:ActivityRecord{7b22489 u0 com.android.settings/.biometrics.fingerprint.FingerprintSettings t10}, backType=TYPE_CROSS_ACTIVITY
02-07 14:15:45.990  2557  2580 D ShellBackPreview: Received backNavigationInfo:BackNavigationInfo{mType=TYPE_CROSS_ACTIVITY (2), mOnBackNavigationDone=android.os.RemoteCallback@cbef809, mOnBackInvokedCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@cd88a0e, mPrepareRemoteAnimation=false, mAnimationCallback=false, mCustomizeAnimationInfo=null}
02-07 14:15:46.000  1873  3897 I InputDispatcher: Channel [Gesture Monitor] edge-swipe (server) is stealing touch from [6c240c0 com.android.settings/com.android.settings.biometrics.fingerprint.FingerprintSettings (server), [Gesture Monitor] swipe-up (server)]
02-07 14:15:46.048  2820  2832 I native  : I0000 00:00:1707333346.048271    2832 tf_lite_classifier.cc:400] Event stream classified as kNone
02-07 14:15:46.050  2557  2580 D ShellBackPreview: Finishing gesture with event action: 1
02-07 14:15:46.050  2557  2580 D ShellBackPreview: onGestureFinished() mTriggerBack == true
02-07 14:15:46.050  2557  2580 D ShellBackPreview: BackAnimationController: finishBackNavigation()
02-07 14:15:46.051  1873  3032 D CoreBackPreview: onBackNavigationDone backType=2, triggerBack=true
02-07 14:15:46.052  2557  2580 V WindowManagerShell: Transition requested: android.os.BinderProxy@d97391a TransitionRequestInfo { type = 2, triggerTask = null, remoteTransition = null, displayChange = null, flags = 0 }
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: Failed to query experiment provider
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Bundle android.content.ContentProviderClient.call(java.lang.String, java.lang.String, android.os.Bundle)' on a null object reference
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at com.google.android.settings.experiments.PhenotypeProxy.getFlagByPackageAndKey(Unknown Source:0)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at com.google.android.settings.experiments.PhenotypeProxy.getBooleanFlagByPackageAndKey(Unknown Source:0)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at com.google.android.settings.overlay.FeatureFactoryImpl.getSurveyFeatureProvider(Unknown Source:0)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at com.android.settings.survey.SurveyMixin.onResume(SurveyMixin.java:57)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at com.android.settingslib.core.lifecycle.Lifecycle.onResume(Lifecycle.java:142)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at com.android.settingslib.core.lifecycle.Lifecycle.-$$Nest$monResume(Lifecycle.java:0)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at com.android.settingslib.core.lifecycle.Lifecycle$LifecycleProxy.onLifecycleEvent(Lifecycle.java:225)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at java.lang.reflect.Method.invoke(Native Method)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:228)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:199)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:191)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:40)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:314)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.kt:251)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.kt:287)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.kt:136)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.kt:119)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at com.android.settingslib.core.lifecycle.ObservablePreferenceFragment.onResume(ObservablePreferenceFragment.java:87)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at com.android.settings.core.InstrumentedPreferenceFragment.onResume(InstrumentedPreferenceFragment.java:91)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at com.android.settings.SettingsPreferenceFragment.onResume(SettingsPreferenceFragment.java:212)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at com.android.settings.dashboard.DashboardFragment.onResume(DashboardFragment.java:241)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at com.android.settings.biometrics.combination.BiometricsSettingsBase.onResume(BiometricsSettingsBase.java:147)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at androidx.fragment.app.Fragment.performResume(Fragment.java:3191)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:643)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:296)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1451)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3029)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:2961)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:285)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:333)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:322)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at android.app.Activity.performResume(Activity.java:8814)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4993)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5036)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:180)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2468)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at android.os.Looper.loopOnce(Looper.java:205)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at android.os.Looper.loop(Looper.java:294)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at android.app.ActivityThread.main(ActivityThread.java:8244)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at java.lang.reflect.Method.invoke(Native Method)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
02-07 14:15:46.069  3004  3004 E PhenotypeProxy: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
02-07 14:15:46.070  3004  3004 I ActiveUnlockStatusUtils: authority not set
02-07 14:15:46.071  3004  3004 I ActiveUnlockStatusUtils: authority not set
02-07 14:15:46.072  3004  3004 I ActiveUnlockStatusUtils: authority not set
02-07 14:15:46.072  3004  3082 D SettingsActivity: No enabled state changed, skipping updateCategory call
02-07 14:15:46.073  3004  3004 I ActiveUnlockStatusUtils: authority not set
02-07 14:15:46.073  3004  3004 I ActiveUnlockStatusUtils: authority not set
02-07 14:15:46.074  3004  3004 I ActiveUnlockStatusUtils: authority not set
02-07 14:15:46.074  1873  3032 D WifiNl80211Manager: Scan result ready event
02-07 14:15:46.074  1873  3032 D WifiNative: Scan result ready event
02-07 14:15:46.074  3004  3004 I ActiveUnlockStatusUtils: authority not set
02-07 14:15:46.074  2744  2767 I LOWI-9.0.0.89.f: [LOWI-Scan] lowi_close_record:Scan done in 93623ms, 4 APs in scan results
02-07 14:15:46.074  3004  3004 I ActiveUnlockStatusUtils: authority not set
02-07 14:15:46.075  3004  3004 I ActiveUnlockStatusUtils: authority not set
02-07 14:15:46.076  3004  3004 I ActiveUnlockStatusUtils: authority not set
02-07 14:15:46.077  3004  3004 I ActiveUnlockStatusUtils: authority not set
02-07 14:15:46.078  3004  3004 I ActiveUnlockStatusUtils: authority not set
02-07 14:15:46.078  3004  3004 I ActiveUnlockStatusUtils: authority not set
```

**Comment by zahidmgsk** [comment]
Log seems purely Source related issue & I will try to fix that at my own because source DEVs are unable to accept the issue is at source side, the same issue is in CrDroid Android 14, 

All AOSP based ROMs are fine no fingerprint issue at all.

**Comment by zahidmgsk** [comment]
I build Lineage 21 & fingerprint sensor is working fine, CrDroid rebased & working fine.

**Comment by zahidmgsk** [comment]
Closing Issue as this is only present in Matrixx & CrDroid sources,
